In [9]:
import tensorflow as tf

In [10]:
print(tf.version.VERSION)

2.4.0-rc0


In [11]:
x=2/3
y=1/3
print(f'x={x: .2f}, y={y: .2f}')

x= 0.67, y= 0.33


range型とタプル型はlistと違い書き変えられない

In [12]:
y = range(5)
print(y)

range(0, 5)


In [13]:
# z = list(range)

In [14]:
z = range(5)
print(z[0], z[3])

0 3


## 2.9 ベクトル
Numpy
Pythonでベクトルと行列を扱うライブラリ

In [15]:
import numpy as np

In [16]:
# ベクトルの定義の仕方
x = np.array([1, 2])
x

array([1, 2])

In [17]:
# ベクトル同士の足し算はNumPyを使わないとできない
a = [1, 2] + [3, 4]
print(f'[1, 2]+[3, 4]={a}')

# NumPyの使い方
x = np.array([1, 2])
y = np.array([3, 4])
print(x+y)

type(x)

[1, 2]+[3, 4]=[1, 2, 3, 4]
[4 6]


numpy.ndarray

要素の参照・書き換えはリスト型同様

In [18]:
# 連続した整数ベクトルの作成
print(f'np.arange(10) = {np.arange(10)}')
print(f'np.arange(5, 10) = {np.arange(5, 10)}')

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(5, 10) = [5 6 7 8 9]


### ndarrayの注意点
b = a
だとbにはaの保存先の参照が渡される（中身）
つまりbを変更するとaも変更される \
b = a.copy()とする 

list型でも同様のことが起こるから　\
b = copy.deepcopy(a)とする

## 2.10 行列
何行何列かと言うことを、行列のサイズという

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print('()で囲まれているからタプル型')

(2, 3)
()で囲まれているからタプル型


In [20]:
# 行列のサイズの変更
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a = a.reshape(2, 5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# 要素を元に戻す
b = a.reshape(10)
print(b)

# もしくは　こっちの方が要素数を調べなくていいので便利
c = a.reshape(-1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 2.10.7 行列やベクトルの連結

### 行列
横に連結するには np.c_[]

In [23]:
x0 = np.array([[1, 2], [3, 4]])
x1 = np.array([[100, 200], [3, 4]])

y = np.c_[x0, x1]
print(y)

[[  1   2 100 200]
 [  3   4   3   4]]


縦に連結するにはnp.r_[]

In [24]:
y = np.r_[x0, x1]
print(y)

[[  1   2]
 [  3   4]
 [100 200]
 [  3   4]]


### ベクトル
ベクトルを立てベクトルとして解釈し、横に連結

In [26]:
# ベクトルの定義
v0 = np.array([1, 2, 3])
v1 = np.array([100, 200, 300])
z = np.c_[v0, v1]
print(z)

[[  1 100]
 [  2 200]
 [  3 300]]


## 2.11 行列の演算

### 算術関数
平方根はnp.sqrt(x)

他にもstd(標準偏差などがある)

In [30]:
x = np.array([[4, 4, 4], [9, 9, 9]])
print(np.sqrt(x))

[[2. 2. 2.]
 [3. 3. 3.]]


### 行列積の計算

In [31]:
v = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([[1, 1], [2, 2], [3, 3]])

print(v @ w)

[[14 14]
 [32 32]]


## 2.12 スライシング

In [34]:
# 変数名[n1:n2:dn]とすると、dnおきに参照される
x = np.arange(10)
print(x[2:9:2])

[2 4 6 8]


In [36]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [40]:
# 二次元以上のndarrayにも使える
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
print(y[1:, 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


## 2.13 条件を満たすデータの書き換え

In [41]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [42]:
x[x > 3]

array([ 5,  8, 13])

## 2.14 HELP

In [44]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

## 2.15
2.15.3 位置引数とキーワード引数

In [46]:
# 位置引数とキーワード引数を同時に使うこともでき
# その場合位置引数を先に書く
# func(1, gamma=3, beta=2)

## 2.16 ファイル保存
1つのndarray型の保存

In [50]:
import numpy as np

data = np.array([1, 2, 3, 3, 5, 8, 20])
print(data)

np.save("datafile.npy", data)

data = np.array([])
print(data)

data = np.load("datafile.npy")
print(data)

[ 1  2  3  3  5  8 20]
[]
[ 1  2  3  3  5  8 20]


複数の型の保存
np.savezを使う

In [53]:
x0 = np.array([1, 2, 3])
x1 = np.array([10, 20, 30])

np.savez("datafile2.npz", x0=x0, x1=x1)

x0 = np.array([])
x1 = np.array([])

data = np.load("datafile2.npz")

print(data.files)  # 格納してる全変数名の表示

x0 = data["x0"]
x1 = data["x1"]

print(x0)
print(x1)

['x0', 'x1']
[1 2 3]
[10 20 30]
