In [9]:
import tensorflow as tf

In [10]:
print(tf.version.VERSION)

2.4.0-rc0


In [11]:
x=2/3
y=1/3
print(f'x={x: .2f}, y={y: .2f}')

x= 0.67, y= 0.33


range型とタプル型はlistと違い書き変えられない

In [12]:
y = range(5)
print(y)

range(0, 5)


In [13]:
# z = list(range)

In [14]:
z = range(5)
print(z[0], z[3])

0 3


## 2.9 ベクトル
Numpy
Pythonでベクトルと行列を扱うライブラリ

In [15]:
import numpy as np

In [16]:
# ベクトルの定義の仕方
x = np.array([1, 2])
x

array([1, 2])

In [17]:
# ベクトル同士の足し算はNumPyを使わないとできない
a = [1, 2] + [3, 4]
print(f'[1, 2]+[3, 4]={a}')

# NumPyの使い方
x = np.array([1, 2])
y = np.array([3, 4])
print(x+y)

type(x)

[1, 2]+[3, 4]=[1, 2, 3, 4]
[4 6]


numpy.ndarray

要素の参照・書き換えはリスト型同様

In [18]:
# 連続した整数ベクトルの作成
print(f'np.arange(10) = {np.arange(10)}')
print(f'np.arange(5, 10) = {np.arange(5, 10)}')

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(5, 10) = [5 6 7 8 9]


### ndarrayの注意点
b = a
だとbにはaの保存先の参照が渡される（中身）
つまりbを変更するとaも変更される　///
b = a.copy()とする ///

list型でも同様のことが起こるから　///
b = copy.deepcopy(a)とする

## 2.10 行列
何行何列かと言うことを、行列のサイズという

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print('()で囲まれているからタプル型')

(2, 3)
()で囲まれているからタプル型


In [20]:
# 行列のサイズの変更
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a = a.reshape(2, 5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# 要素を元に戻す
b = a.reshape(10)
print(b)

# もしくは　こっちの方が要素数を調べなくていいので便利
c = a.reshape(-1)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## 2.10.7 行列やベクトルの連結

### 行列
横に連結するには np.c_[]

In [23]:
x0 = np.array([[1, 2], [3, 4]])
x1 = np.array([[100, 200], [3, 4]])

y = np.c_[x0, x1]
print(y)

[[  1   2 100 200]
 [  3   4   3   4]]


縦に連結するにはnp.r_[]

In [24]:
y = np.r_[x0, x1]
print(y)

[[  1   2]
 [  3   4]
 [100 200]
 [  3   4]]


### ベクトル
ベクトルを立てベクトルとして解釈し、横に連結

In [26]:
# ベクトルの定義
v0 = np.array([1, 2, 3])
v1 = np.array([100, 200, 300])
z = np.c_[v0, v1]
print(z)

[[  1 100]
 [  2 200]
 [  3 300]]


## 2.11 行列の演算